import { Lemonada } from "next/font/google";
import "./globals.css";
import SubNavbar from "@/components/subNavbar/SubNavbar";
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";

const lemonadaFont=Lemonada({
   subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-lemonada",
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lemonadaFont.variable} ${lemonadaFont.variable}`}>
        <SubNavbar/>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
